name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/*.apk

      - name: Show APK filename
        run: |
           shopt -s nullglob
           apk_files=(*.apk)
          if [ ${#apk_files[@]} -eq 0 ]; then
             echo "No APK files found"
          else
             echo "APK files found:"
             for file in "${apk_files[@]}"; do
              echo "$file"
             done
          fi
